blank_issues_enabled: true
contact_links:
  - name: Question / Discussion
    url: https://github.com/Y-Ysss/vscode-cisco-config-highlight/discussions
    about: Ask questions or discuss ideas outside actionable issues.
